Completed javascript-ajax exercise.
samlee0258/rc0123-code-solutions pull request #65
Opened 2023-02-23 22:09 UTC by samlee0258

<img width="1164" alt="Screenshot 2023-02-23 at 2 07 45 PM" src="https://user-images.githubusercontent.com/110208589/221041787-58d0c9d4-28fa-4c95-82a0-185a3798007e.png">

2023-02-23 22:26 UTC, robgmerrill requested changes
Good start! One change requested.

2023-02-23 22:26 UTC, robgmerrill commented on javascript-ajax/users.js
> +  for (var key in xhr.response) {
for...in loops shouldn't be used on arrays. They should be reserved for objects. While it works in this case it is best to avoid. This can be replaced with a normal for loop. Reach out via slack if you have any questions about that!

2023-02-23 23:03 UTC, samlee0258 commented on javascript-ajax/users.js
> +  for (var key in xhr.response) {
<img width="657" alt="Screenshot 2023-02-23 at 3 03 16 PM" src="https://user-images.githubusercontent.com/110208589/221050878-a7d8a7ab-3db7-4edf-b4b3-12fb6d098fcb.png">

2023-02-24 00:25 UTC, robgmerrill approved these changes
👍

2023-02-24 09:14 UTC, merged